### ISSUE TITLE
The broken font troubleshooter mentions fixing the issue on Windows 10, despite running fine on Windows 11

### ISSUE THREAD

**Issue by gus33000** [File-New-Project/TroubleshootingPacks#2]
![image](https://github.com/File-New-Project/TroubleshootingPacks/assets/3755345/f5bed5fb-8030-4386-9809-664f74f2d13d)

Expected behavior: correct windows branding is shown, or generic information is shown, or the tool only runs on Windows 10

**Comment by riverar** [comment]
Fixed in https://github.com/File-New-Project/TroubleshootingPacks/commit/37fa8e4e987c4b708286f4be2e153c5d2547c7ba. This issue doesn't affect upgrades to Windows 11 but broadening the scope doesn't hurt either.
